APP_IMAGES_ = "C:/Users/Krishna Pratap/PycharmProjects/WeatherApp/Images/"
background = "%sbackground.jpg" % APP_IMAGES_
ajaxLoader = "%sajax-loader.gif" % APP_IMAGES_
amtmosphericPressure = "%sAtmospheric Pressure-44 (1).png" % APP_IMAGES_
cancel = "%sCancel_20px.png" % APP_IMAGES_
cloud64 = "%sCloud_64px.png" % APP_IMAGES_
could100 = "%sCloud_100px.png" % APP_IMAGES_
download = "%sdownload.jpg" % APP_IMAGES_
humidity44 = "%sHumidity_44px.png" % APP_IMAGES_
marker64 = "%sMarker_64px.png" % APP_IMAGES_
minux20 = "%sMinus_20px.png" % APP_IMAGES_
rain64 = "%sRain_64px_1.png" % APP_IMAGES_
rain100 = "%sRain_100px.png" % APP_IMAGES_
refresh15 = "%sRefresh_15px.png" % APP_IMAGES_
ring = "%sring.gif" % APP_IMAGES_
snow64 = "%ssnow64px.png" % APP_IMAGES_
snow100 = "%sSnow_100px.png" % APP_IMAGES_
snow128 = "%ssnow128px.png" % APP_IMAGES_
sun64 = "%sSun_64px_3.png" % APP_IMAGES_
sun100 = "%sSun_100px.png" % APP_IMAGES_
temperture32 = "%sTemperature_32px.png" % APP_IMAGES_
thermometer44 = "%sThermometer-44.png" % APP_IMAGES_
thermometer64 = "%sThermometer-64.png" % APP_IMAGES_
user20 = "%sUser_20px.png" % APP_IMAGES_
windSpeed44 = "%sWind Speed 98-102_44px.png" % APP_IMAGES_
moonstar64 = "%smoon-and-star-outlines64px.png" % APP_IMAGES_
moonstar128 = "%smoon-and-star-outlines128px.png" % APP_IMAGES_
moon64 = "%smoon-phase-black-crescent-shape64px.png" % APP_IMAGES_
moon128 = "%smoon-phase-black-crescent-shape128px.png" % APP_IMAGES_
raindrops64 = "%srain-black-cloud-with-raindrops-falling-down64px.png" % APP_IMAGES_
raindrops128 = "%srain-black-cloud-with-raindrops-falling-down128px.png" % APP_IMAGES_
suncloud64 = "%ssun-and-cloud64px.png" % APP_IMAGES_
suncloud128 = "%ssun-and-cloud128px.png" % APP_IMAGES_
thunderstorm64 = "%sthunderstorm-clouds64px.png" % APP_IMAGES_
thunderstorm128 = "%sthunderstorm-clouds128px.png" % APP_IMAGES_
cloudnight64 = "%sdark-night64px.png" % APP_IMAGES_
cloudnight128 = "%sdark-night128px.png" % APP_IMAGES_
snowcloud64 = "%scloud-with-snowflakes-weather-symbol64px.png" % APP_IMAGES_
snowcloud128 = "%scloud-with-snowflakes-weather-symbol128px.png" % APP_IMAGES_
sleet64 = "%ssleet64.png" % APP_IMAGES_
sleet128 = "%ssleet128px.png" % APP_IMAGES_
foggyday64 = "%sfoggy-day64.png" % APP_IMAGES_
foggyday128 = "%sfoggy-day128px.png" % APP_IMAGES_
wind64 = "%swind64px.png" % APP_IMAGES_
wind128 = "%swind128px.png" % APP_IMAGES_
cloud128 = "%sclouds-outlined-weather-symbol128px.png" % APP_IMAGES_
sun128 = "%ssun-day-weather-symbol128px.png" % APP_IMAGES_
rain128 = "%srainy-day128px.png" % APP_IMAGES_
rain24 = "%srainy-day24.png" % APP_IMAGES_
cloudy24 = "%scloudy24.png" % APP_IMAGES_
cloudynight24 = "%srainy-day24.png" % APP_IMAGES_
cloudysun24 = "%srainy-day24.png" % APP_IMAGES_
sleet24 = "%ssleet24.png" % APP_IMAGES_
clearnight24 = "%sclear_night24.png" % APP_IMAGES_
fog24 = "%sfog24.png" % APP_IMAGES_
snow24 = "%srainy-day24.png" % APP_IMAGES_
wind24 = "%swind24.png" % APP_IMAGES_
background2 = "%sclouds-dark-dark-clouds-416920.jpg" % APP_IMAGES_


percentsign = "%"
degreesign = "°"
degree_celsius = "°C"

hostAddress = 'https://maps.googleapis.com/maps/api/geocode/json?address='
googleAPIKey = 'AIzaSyBIbymudRAW7AZ7EgRdhX9HMoWo7dyI0-k'

hostWeather = 'https://api.darksky.net/forecast/'
darkSkyAPI = '603a7a03907fde11551d5ad6455eb697'
